Not quite working yet, but a lot of the configuration stuff is seemingly covered now. Custom bin includes scripts for new installs, configuring a CA, server cert/key, client cert/key. Just need to get the damn thing to start now!

diff --git a/openvpn/bin/entrypoint b/openvpn/bin/entrypoint
--- a/openvpn/bin/entrypoint
+++ b/openvpn/bin/entrypoint
@@ -14,12 +14,12 @@ if [[ ! -e $OVPN_DIR/server.conf ]]; then
 	# The config dir hasn't been initialized
 	# Run the install script
 	openvpn_install
-else
+#else
 	# Looks like OpenVPN is already installed
-	echo $OVPN_DIR/server.conf found. Not going to run openvpn_install.
+	# echo $OVPN_DIR/server.conf found. Not going to run openvpn_install.
 fi
 
-IMAGE="annixa/dockerlab-vpn"
+export IMAGE="dockerlabvpn_vpn"
 
 if [ -z ${IMAGE+x} ]; then
 	echo Error: IMAGE variable is required. && exit 1
@@ -28,11 +28,14 @@ fi
 # Check for the pki configuration
 if [ ! -d $OVPN_DIR/easy-rsa ]; then
 	# The easy-rsa dir hasn't been initialized
-	# Let the user know that they need to run the initpki script
-	echo -e "$OVPN_DIR/easy-rsa not found. You can initialize it by running:\n"
-	echo -e "docker run -it $IMAGE openvpn_initpki\n"
-	echo -e "(Or you can just map in the /etc/openvpn/easy-rsa using a volume.)"
-	exit 1
+
+	if [ "$1" != "openvpn_initpki" ]; then
+		# Let the user know that they need to run the initpki script
+		echo -e "PKI configuration not found. You can initialize it now by running:\n"
+		echo -e "docker run --rm --volumes-from $OVPN_DATA -it $IMAGE openvpn_initpki\n"
+		echo -e "(Or you can just map in $OVPN_DIR/easy-rsa using a volume?)"
+		exit 1
+	fi
 fi
 
 
